### ISSUE TITLE
No attributes released in saml sso.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxShibboleth#155]
### Describe the issue 

no  attributes released in saml response.
 
### How to reproduce 

1. go to admin console
2. go to saml ->  add new trust relationship
3. test trust relationship with samltest.id or any sp

### Expected behaviour 

user must get attributes with values when sign in on sp 

### Actual behaviour

user is able authenticate but no attribute released.

### System
Gluu-version:-4.5 + postgresql

OS :- Ubuntu22.04

### error on log

```
2022-10-13 07:15:52,245 - 103.47.14.59 - INFO [org.gluu.oxauth.client.OpenIdClient:136] - Successfully loaded oxAuth configuration
2022-10-13 07:15:52,886 - 103.47.14.59 - INFO [org.gluu.idp.externalauth.ShibOxAuthAuthServlet:172] - Processing authorization response
2022-10-13 07:15:53,080 - 103.47.14.59 - INFO [org.gluu.oxauth.client.OpenIdClient:421] - Using default claims to attributes mapping
2022-10-13 07:15:53,435 - 103.47.14.59 - INFO [net.shibboleth.idp.authn.impl.ValidateExternalAuthentication:180] - Profile Action OxAuthValidateExternalAuthentication: External authentication succeeded for Subject
2022-10-13 07:15:53,588 - 103.47.14.59 - INFO [net.shibboleth.idp.authn.impl.FinalizeAuthentication:196] - Profile Action FinalizeAuthentication: Principal admin authenticated
2022-10-13 07:15:53,796 - 103.47.14.59 - WARN [DEPRECATED:132] - Java class method 'requestContext.getPrincipalName()': This will be removed in the next major version of this software; replacement is resolutionContext.getPrincipal()
2022-10-13 07:15:53,809 - 103.47.14.59 - WARN [net.shibboleth.idp.attribute.resolver.impl.AttributeResolverImpl:438] - Attribute Resolver 'ShibbolethAttributeResolver': Data connector 'siteDataConnector' failed
net.shibboleth.idp.attribute.resolver.ResolutionException: Data Connector 'siteDataConnector': Unable to execute SQL query
        at net.shibboleth.idp.attribute.resolver.dc.rdbms.impl.RDBMSDataConnector.retrieveAttributes(RDBMSDataConnector.java:154)
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot load JDBC driver class 'com.pgsql.jdbc.Driver'
        at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1429)
Caused by: java.lang.ClassNotFoundException: com.pgsql.jdbc.Driver
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
2022-10-13 07:15:53,811 - 103.47.14.59 - ERROR [net.shibboleth.idp.profile.impl.ResolveAttributes:317] - Profile Action ResolveAttributes: Error resolving attributes
net.shibboleth.idp.attribute.resolver.ResolutionException: Data Connector 'siteDataConnector': Unable to execute SQL query
        at net.shibboleth.idp.attribute.resolver.dc.rdbms.impl.RDBMSDataConnector.retrieveAttributes(RDBMSDataConnector.java:154)
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot load JDBC driver class 'com.pgsql.jdbc.Driver'
        at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1429)
Caused by: java.lang.ClassNotFoundException: com.pgsql.jdbc.Driver
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
2022-10-13 07:15:53,970 - 103.47.14.59 - INFO [org.gluu.idp.consent.processor.GluuReleaseAttributesPostProcessor:62] - Executing external IDP script
2022-10-13 07:15:54,123 - 103.47.14.59 - WARN [net.shibboleth.idp.saml.nameid.impl.AttributeSourcedSAML2NameIDGenerator:148] - Unable to locate AttributeContext
2022-10-13 07:15:54,298 - 103.47.14.59 - INFO [net.shibboleth.idp.saml.session.impl.SAML2SPSessionCreationStrategy:127] - Creating BasicSPSession in the absence of necessary information
2022-10-13 07:15:54,781 - 103.47.14.59 - INFO [Shibboleth-Audit.SSO:283] - 103.47.14.59|2022-10-13T07:15:50.298148Z|2022-10-13T07:15:54.780555Z|admin|https://samltest.id/saml/sp|_145298ba7c57625bd0a1f545b282e881|password|2022-10-13T07:15:53.451750Z||||false|false|AES128-GCM|Redirect|POST||Success||59db757acfcd0b782f0d1ad4db02fac4323aaa9a755a8c1768d7ad3a71113d29|Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

```

### Screenshots
![Screenshot from 2022-10-13 12-55-28](https://user-images.githubusercontent.com/34593983/195533938-41ad5b14-f7ea-4527-8870-2863c6e83ea2.png)

**Comment by MohitMaliFtechiz** [comment]
The issue is fixed.
