### ISSUE TITLE
Shib IDP doesn't release NameID 

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxShibboleth#17]
NameID generation is enabled in configuration. My IDP test instance does not release it.
Nothing NameID-related has been changed.

**Comment by dmogn** [comment]
2016-10-17 03:45:58,432 - WARN [net.shibboleth.ext.spring.context.FilesystemGenericApplicationContext:545] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'net.shibboleth.idp.saml.nameid.impl.NameIdentifierGenerationServiceImpl#0' defined in file [/opt/shibboleth-idp/system/conf/saml-nameid-system.xml]: Cannot create inner bean 'org.opensaml.saml.saml1.profile.impl.ChainingSAML1NameIdentifierGenerator#688770e0' of type [org.opensaml.saml.saml1.profile.impl.ChainingSAML1NameIdentifierGenerator] while setting bean property 'SAML1NameIdentifierGenerator'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.opensaml.saml.saml1.profile.impl.ChainingSAML1NameIdentifierGenerator#688770e0' defined in file [/opt/shibboleth-idp/system/conf/saml-nameid-system.xml]: Cannot resolve reference to bean 'shibboleth.SAML1NameIdentifierGenerators' while setting bean property 'generators'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'shibboleth.SAML1NameIdentifierGenerators' is defined
2016-10-17 03:45:58,460 - ERROR [net.shibboleth.utilities.java.support.service.AbstractReloadableService:181] - Service 'shibboleth.NameIdentifierGenerationService': Initial load failed
net.shibboleth.utilities.java.support.service.ServiceException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'net.shibboleth.idp.saml.nameid.impl.NameIdentifierGenerationServiceImpl#0' defined in file [/opt/shibboleth-idp/system/conf/saml-nameid-system.xml]: Cannot create inner bean 'org.opensaml.saml.saml1.profile.impl.ChainingSAML1NameIdentifierGenerator#688770e0' of type [org.opensaml.saml.saml1.profile.impl.ChainingSAML1NameIdentifierGenerator] while setting bean property 'SAML1NameIdentifierGenerator'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.opensaml.saml.saml1.profile.impl.ChainingSAML1NameIdentifierGenerator#688770e0' defined in file [/opt/shibboleth-idp/system/conf/saml-nameid-system.xml]: Cannot resolve reference to bean 'shibboleth.SAML1NameIdentifierGenerators' while setting bean property 'generators'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'shibboleth.SAML1NameIdentifierGenerators' is defined
        at net.shibboleth.ext.spring.service.ReloadableSpringService.doReload(ReloadableSpringService.java:334)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'net.shibboleth.idp.saml.nameid.impl.NameIdentifierGenerationServiceImpl#0' defined in file [/opt/shibboleth-idp/system/conf/saml-nameid-system.xml]: Cannot create inner bean 'org.opensaml.saml.saml1.profile.impl.ChainingSAML1NameIdentifierGenerator#688770e0' of type [org.opensaml.saml.saml1.profile.impl.ChainingSAML1NameIdentifierGenerator] while setting bean property 'SAML1NameIdentifierGenerator'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.opensaml.saml.saml1.profile.impl.ChainingSAML1NameIdentifierGenerator#688770e0' defined in file [/opt/shibboleth-idp/system/conf/saml-nameid-system.xml]: Cannot resolve reference to bean 'shibboleth.SAML1NameIdentifierGenerators' while setting bean property 'generators'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'shibboleth.SAML1NameIdentifierGenerators' is defined
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.opensaml.saml.saml1.profile.impl.ChainingSAML1NameIdentifierGenerator#688770e0' defined in file [/opt/shibboleth-idp/system/conf/saml-nameid-system.xml]: Cannot resolve reference to bean 'shibboleth.SAML1NameIdentifierGenerators' while setting bean property 'generators'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'shibboleth.SAML1NameIdentifierGenerators' is defined
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'shibboleth.SAML1NameIdentifierGenerators' is defined
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:698)
2016-10-17 03:57:53,772 - WARN [org.opensaml.saml.common.profile.logic.MetadataNameIdentifierFormatStrategy:75] - Ignoring NameIDFormat metadata that includes the 'unspecified' format
2016-10-17 03:57:53,816 - ERROR [org.opensaml.saml.saml2.profile.impl.AddNameIDToSubjects:404] - Profile Action AddNameIDToSubjects: Error while generating NameID
org.opensaml.saml.common.SAMLException: Invalid NameIdentifierGenerationService configuration
        at net.shibboleth.idp.saml.nameid.impl.ProxySAML2NameIDGenerator.generate(ProxySAML2NameIDGenerator.java:62)

**Comment by dmogn** [comment]
I should return back some SAML1 functionality, because SAM2 NameID use it.

https://github.com/GluuFederation/oxShibboleth/issues/11

**Comment by nynymike** [comment]
Ok
