### ISSUE TITLE
Google SSO with Shibboleth is broken

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxShibboleth#32]
I am getting following error on browser after getting redirected from admin.google.com 

https://host/idp/profile/SAML2/Redirect/SSO?SAMLRequest=xxxxxx&RelayState=https%3A%2F%2Faccounts.google.com%2FCheckCookie%3Fcontinue%3Dhttps%253A%252F%252Fadmin.google.com%252FDashboard%26service%3DCPanel%26hl%3Den%26checkedDomains%3Dyoutube%26checkConnection%3Dyoutube%253A161%253A1%26pstMsg%3D1%26skipvpage%3Dtrue
HTTP ERROR 500

Problem accessing /idp/profile/SAML2/Redirect/SSO. Reason:

    Server Error

Caused by:

org.springframework.web.util.NestedServletException: Method invocation failed during rendering of Velocity view with name 'error': Invocation of method 'getMessage' in  class org.springframework.web.servlet.support.RequestContext threw exception org.springframework.context.NoSuchMessageException: No message found under code 'idp.logo' for locale 'en_US'. at org/springframework/web/servlet/view/velocity/spring.vm[line 27, column 57]; reference [springMacroRequestContext], method 'getMessage'; nested exception is org.springframework.context.NoSuchMessageException: No message found under code 'idp.logo' for locale 'en_US'.
	at org.springframework.web.servlet.view.velocity.VelocityView.mergeTemplate(VelocityView.java:526)
	at org.springframework.web.servlet.view.velocity.VelocityView.doRender(VelocityView.java:464)
	at org.springframework.web.servlet.view.velocity.VelocityView.renderMergedTemplateModel(VelocityView.java:294)
	at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:167)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1257)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at net.shibboleth.idp.log.SLF4JMDCServletFilter.doFilter(SLF4JMDCServletFilter.java:72)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at net

**Comment by dmogn** [comment]
Fixed with: https://github.com/GluuFederation/oxShibboleth/issues/31
