### ISSUE TITLE
Shib configuration is trying to load 'openldap.crt' in 'gluu-openDJ' setup

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxShibboleth#37]
oxShibboleth should detect ldap cert accordingly; in latest 3.1.2 when we install a Gluu Server with 'gluu-OpenDJ'; 'idp-process.log' is throwing below error. 
I am not exactly sure how it's looking for 'openldap.crt' specifically but it should look for 'opendj.crt' for OpenDJ based installation. 

Here is what idp-process.log saying: 

```
2018-02-07 10:36:40,566 - ERROR [net.shibboleth.idp.profile.spring.factory.BasicX509CredentialFactoryBean:180] - null: could not decode CertificateFile at class path resource [etc/certs/openldap.crt]: {}
java.io.FileNotFoundException: class path resource [etc/certs/openldap.crt] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:172)
2018-02-07 10:36:40,583 - WARN [net.shibboleth.ext.spring.context.FilesystemGenericApplicationContext:549] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteLDAP': Cannot create inner bean '(inner bean)#95ed5f4' of type [org.ldaptive.DefaultConnectionFactory] while setting bean property 'connectionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#95ed5f4': Cannot create inner bean '(inner bean)#30a92d4b' of type [org.ldaptive.ConnectionConfig] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#30a92d4b': Cannot create inner bean '(inner bean)#612af1ea' of type [org.ldaptive.ssl.SslConfig] while setting bean property 'sslConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#612af1ea': Cannot create inner bean '(inner bean)#40263b8c' of type [net.shibboleth.idp.attribute.resolver.spring.dc.ldap.impl.CredentialConfigFactoryBean] while setting bean property 'credentialConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#40263b8c': Cannot create inner bean '(inner bean)#763527c3' of type [net.shibboleth.idp.profile.spring.factory.BasicX509CredentialFactoryBean] while setting bean property 'trustCredential'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#763527c3': Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided CertificateFile: class path resource [etc/certs/openldap.crt]; nested exception is java.io.FileNotFoundException: class path resource [etc/certs/openldap.crt] cannot be opened because it does not exist
2018-02-07 10:36:40,585 - ERROR [net.shibboleth.utilities.java.support.service.AbstractReloadableService:231] - Service 'shibboleth.AttributeResolverService': Reload for shibboleth.AttributeResolverService failed
net.shibboleth.utilities.java.support.service.ServiceException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteLDAP': Cannot create inner bean '(inner bean)#95ed5f4' of type [org.ldaptive.DefaultConnectionFactory] while setting bean property 'connectionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#95ed5f4': Cannot create inner bean '(inner bean)#30a92d4b' of type [org.ldaptive.ConnectionConfig] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#30a92d4b': Cannot create inner bean '(inner bean)#612af1ea' of type [org.ldaptive.ssl.SslConfig] while setting bean property 'sslConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#612af1ea': Cannot create inner bean '(inner bean)#40263b8c' of type [net.shibboleth.idp.attribute.resolver.spring.dc.ldap.impl.CredentialConfigFactoryBean] while setting bean property 'credentialConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#40263b8c': Cannot create inner bean '(inner bean)#763527c3' of type [net.shibboleth.idp.profile.spring.factory.BasicX509CredentialFactoryBean] while setting bean property 'trustCredential'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#763527c3': Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided CertificateFile: class path resource [etc/certs/openldap.crt]; nested exception is java.io.FileNotFoundException: class path resource [etc/certs/openldap.crt] cannot be opened because it does not exist
	at net.shibboleth.ext.spring.service.ReloadableSpringService.doReload(ReloadableSpringService.java:336)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteLDAP': Cannot create inner bean '(inner bean)#95ed5f4' of type [org.ldaptive.DefaultConnectionFactory] while setting bean property 'connectionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#95ed5f4': Cannot create inner bean '(inner bean)#30a92d4b' of type [org.ldaptive.ConnectionConfig] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#30a92d4b': Cannot create inner bean '(inner bean)#612af1ea' of type [org.ldaptive.ssl.SslConfig] while setting bean property 'sslConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#612af1ea': Cannot create inner bean '(inner bean)#40263b8c' of type [net.shibboleth.idp.attribute.resolver.spring.dc.ldap.impl.CredentialConfigFactoryBean] while setting bean property 'credentialConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#40263b8c': Cannot create inner bean '(inner bean)#763527c3' of type [net.shibboleth.idp.profile.spring.factory.BasicX509CredentialFactoryBean] while setting bean property 'trustCredential'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#763527c3': Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided CertificateFile: class path resource [etc/certs/openldap.crt]; nested exception is java.io.FileNotFoundException: class path resource [etc/certs/openldap.crt] cannot be opened because it does not exist
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#95ed5f4': Cannot create inner bean '(inner bean)#30a92d4b' of type [org.ldaptive.ConnectionConfig] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#30a92d4b': Cannot create inner bean '(inner bean)#612af1ea' of type [org.ldaptive.ssl.SslConfig] while setting bean property 'sslConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#612af1ea': Cannot create inner bean '(inner bean)#40263b8c' of type [net.shibboleth.idp.attribute.resolver.spring.dc.ldap.impl.CredentialConfigFactoryBean] while setting bean property 'credentialConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#40263b8c': Cannot create inner bean '(inner bean)#763527c3' of type [net.shibboleth.idp.profile.spring.factory.BasicX509CredentialFactoryBean] while setting bean property 'trustCredential'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#763527c3': Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided CertificateFile: class path resource [etc/certs/openldap.crt]; nested exception is java.io.FileNotFoundException: class path resource [etc/certs/openldap.crt] cannot be opened because it does not exist
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#30a92d4b': Cannot create inner bean '(inner bean)#612af1ea' of type [org.ldaptive.ssl.SslConfig] while setting bean property 'sslConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#612af1ea': Cannot create inner bean '(inner bean)#40263b8c' of type [net.shibboleth.idp.attribute.resolver.spring.dc.ldap.impl.CredentialConfigFactoryBean] while setting bean property 'credentialConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#40263b8c': Cannot create inner bean '(inner bean)#763527c3' of type [net.shibboleth.idp.profile.spring.factory.BasicX509CredentialFactoryBean] while setting bean property 'trustCredential'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#763527c3': Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided CertificateFile: class path resource [etc/certs/openldap.crt]; nested exception is java.io.FileNotFoundException: class path resource [etc/certs/openldap.crt] cannot be opened because it does not exist
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#612af1ea': Cannot create inner bean '(inner bean)#40263b8c' of type [net.shibboleth.idp.attribute.resolver.spring.dc.ldap.impl.CredentialConfigFactoryBean] while setting bean property 'credentialConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#40263b8c': Cannot create inner bean '(inner bean)#763527c3' of type [net.shibboleth.idp.profile.spring.factory.BasicX509CredentialFactoryBean] while setting bean property 'trustCredential'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#763527c3': Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided CertificateFile: class path resource [etc/certs/openldap.crt]; nested exception is java.io.FileNotFoundException: class path resource [etc/certs/openldap.crt] cannot be opened because it does not exist
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#40263b8c': Cannot create inner bean '(inner bean)#763527c3' of type [net.shibboleth.idp.profile.spring.factory.BasicX509CredentialFactoryBean] while setting bean property 'trustCredential'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#763527c3': Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided CertificateFile: class path resource [etc/certs/openldap.crt]; nested exception is java.io.FileNotFoundException: class path resource [etc/certs/openldap.crt] cannot be opened because it does not exist
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#763527c3': Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided CertificateFile: class path resource [etc/certs/openldap.crt]; nested exception is java.io.FileNotFoundException: class path resource [etc/certs/openldap.crt] cannot be opened because it does not exist
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
Caused by: org.springframework.beans.FatalBeanException: Could not decode provided CertificateFile: class path resource [etc/certs/openldap.crt]; nested exception is java.io.FileNotFoundException: class path resource [etc/certs/openldap.crt] cannot be opened because it does not exist
	at net.shibboleth.idp.profile.spring.factory.BasicX509CredentialFactoryBean.getCertificates(BasicX509CredentialFactoryBean.java:182)
Caused by: java.io.FileNotFoundException: class path resource [etc/certs/openldap.crt] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:172)
2018-02-07 10:36:41,158 - INFO [net.shibboleth.utilities.java.support.service.AbstractReloadableService:258] - Service 'shibboleth.RelyingPartyResolverService': Reloading service configuration
2018-02-07 10:36:41,160 - INFO [net.shibboleth.ext.spring.util.SchemaTypeAwareXMLBeanDefinitionReader:317] - Loading XML bean definitions from file [/opt/shibboleth-idp/conf/relying-party.xml]
2018-02-07 10:36:41,175 - INFO [net.shibboleth.ext.spring.util.SchemaTypeAwareXMLBeanDefinitionReader:317] - Loading XML bean definitions from file [/opt/shibboleth-idp/conf/credentials.xml]
2018-02-07 10:36:41,184 - INFO [net.shibboleth.ext.spring.util.SchemaTypeAwareXMLBeanDefinitionReader:317] - Loading XML bean definitions from file [/opt/shibboleth-idp/system/conf/relying-party-system.xml]
2018-02-07 10:36:41,198 - INFO [net.shibboleth.ext.spring.context.FilesystemGenericApplicationContext:581] - Refreshing ApplicationContext:shibboleth.RelyingPartyResolverService: startup date [Wed Feb 07 10:36:41 UTC 2018]; parent: Root WebApplicationContext
2018-02-07 10:36:41,254 - INFO [net.shibboleth.utilities.java.support.service.AbstractReloadableService:258] - Service 'shibboleth.ReloadableCASServiceRegistry': Reloading service configuration
2018-02-07 10:36:41,256 - INFO [net.shibboleth.ext.spring.util.SchemaTypeAwareXMLBeanDefinitionReader:317] - Loading XML bean definitions from file [/opt/shibboleth-idp/conf/cas-protocol.xml]
2018-02-07 10:36:41,273 - INFO [net.shibboleth.ext.spring.context.FilesystemGenericApplicationContext:581] - Refreshing ApplicationContext:shibboleth.ReloadableCASServiceRegistry: startup date [Wed Feb 07 10:36:41 UTC 2018]; parent: Root WebApplicationContext
2018-02-07 10:36:41,304 - INFO [net.shibboleth.ext.spring.service.ReloadableSpringService:380] - Service 'shibboleth.ReloadableCASServiceRegistry': Completed reload and swapped in latest configuration for service 'shibboleth.ReloadableCASServiceRegistry'
2018-02-07 10:36:41,305 - INFO [net.shibboleth.ext.spring.context.FilesystemGenericApplicationContext:982] - Closing ApplicationContext:shibboleth.ReloadableCASServiceRegistry: startup date [Wed Feb 07 10:21:41 UTC 2018]; parent: Root WebApplicationContext
2018-02-07 10:36:41,306 - INFO [net.shibboleth.ext.spring.service.ReloadableSpringService:387] - Service 'shibboleth.ReloadableCASServiceRegistry': Reload complete
2018-02-07 10:36:41,455 - INFO [net.shibboleth.ext.spring.service.ReloadableSpringService:380] - Service 'shibboleth.RelyingPartyResolverService': Completed reload and swapped in latest configuration for service 'shibboleth.RelyingPartyResolverService'
2018-02-07 10:36:41,456 - INFO [net.shibboleth.ext.spring.context.FilesystemGenericApplicationContext:982] - Closing ApplicationContext:shibboleth.RelyingPartyResolverService: startup date [Wed Feb 07 10:21:40 UTC 2018]; parent: Root WebApplicationContext
2018-02-07 10:36:41,461 - INFO [net.shibboleth.ext.spring.service.ReloadableSpringService:387] - Service 'shibboleth.RelyingPartyResolverService': Reload complete
[root@ksutest logs]# cd /opt/shibboleth-idp/conf/

```

Version: 

1. 
```
Manifest-Version: 1.0
Implementation-Title: OX Shibboleth IDP
Implementation-Version: 3.1.2.Final
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 
Implementation-Vendor-Id: org.xdi
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_121
```

2. 
```
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.1.2.Final
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 9de781cd23764ec11b234af65cd055d159a83877
Implementation-Vendor-Id: org.xdi
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_121
```

**Comment by yurem** [comment]
Fixed
