### ISSUE TITLE
Error in relying-party.xml when "encryptNameIDs" set to "conditional"

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxShibboleth#40]
Based on [this ](https://support.gluu.org/single-sign-on/5187/shibboleth-does-not-start-because-of-error-in-relying-partyxml/#at31192) ticket, idp service failed to start when using Configure Relying Party and set "encryptNameIDs" to "conditional".

![image](https://user-images.githubusercontent.com/21104811/37435073-df2ac4c2-2807-11e8-881f-417d0b8e1115.png)

GLUU.root@ubuntu:~# service idp restart
Stopping Jetty: OK
Starting Jetty: . . . . . . . . . . . . . . FAILED Wed Mar 14 22:39:53 UTC 2018

GLUU.root@ubuntu:/opt/shibboleth-idp/logs# grep -i -e 'encryptNameIds' /opt/shibboleth-idp/conf/relying-party.xml
p:encryptNameIDs="false"
p:encryptNameIDs="false"
p:encryptNameIDs="false"
p:encryptNameIDs="false"
p:encryptNameIds-ref="EncryptNoConfidentiality"
GLUU.root@ubuntu:/opt/shibboleth-idp/logs#

Error in Logs
at net.shibboleth.ext.spring.service.ReloadableSpringService.doReload(ReloadableSpringService.java:336)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.RelyingPartyOverrides': Cannot create inner bean 'FC74F0095CC370350002DE56040A000654963FC4' of type [net.shibboleth.idp.saml.relyingparty.impl.RelyingPartyConfigurationSupport] while setting bean property 'sourceList' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'FC74F0095CC370350002DE56040A000654963FC4' defined in file [/opt/shibboleth-idp/conf/relying-party.xml]: Cannot create inner bean 'SAML2.SSO$child#1a256d80' of type [net.shibboleth.idp.saml.saml2.profile.config.BrowserSSOProfileConfiguration] while setting bean property 'profileConfigurations' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'SAML2.SSO$child#1a256d80' defined in file [/opt/shibboleth-idp/conf/relying-party.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'encryptNameIds' of bean class [net.shibboleth.idp.saml.saml2.profile.config.BrowserSSOProfileConfiguration]: Bean property 'encryptNameIds' is not writable or has an invalid setter method. Did you mean 'encryptNameIDs'?
at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'FC74F0095CC370350002DE56040A000654963FC4' defined in file [/opt/shibboleth-idp/conf/relying-party.xml]: Cannot create inner bean 'SAML2.SSO$child#1a256d80' of type [net.shibboleth.idp.saml.saml2.profile.config.BrowserSSOProfileConfiguration] while setting bean property 'profileConfigurations' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'SAML2.SSO$child#1a256d80' defined in file [/opt/shibboleth-idp/conf/relying-party.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'encryptNameIds' of bean class [net.shibboleth.idp.saml.saml2.profile.config.BrowserSSOProfileConfiguration]: Bean property 'encryptNameIds' is not writable or has an invalid setter method. Did you mean 'encryptNameIDs'?
at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'SAML2.SSO$child#1a256d80' defined in file [/opt/shibboleth-idp/conf/relying-party.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'encryptNameIds' of bean class [net.shibboleth.idp.saml.saml2.profile.config.BrowserSSOProfileConfiguration]: Bean property 'encryptNameIds' is not writable or has an invalid setter method. Did you mean 'encryptNameIDs'?
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1518)
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'encryptNameIds' of bean class [net.shibboleth.idp.saml.saml2.profile.config.BrowserSSOProfileConfiguration]: Bean property 'encryptNameIds' is not writable or has an invalid setter method. Did you mean 'encryptNameIDs'?
at org.springframework.beans.BeanWrapperImpl.createNotWritablePropertyException(BeanWrapperImpl.java:243)

**Comment by dmogn** [comment]
Done.

**Comment by malotian** [comment]
@dmogn can you let me know the solution

**Comment by nynymike** [comment]
@dmogn  has not worked at Gluu for some time
