### ISSUE TITLE
Seeing SAMLResponse in Header but SP is not getting Assertion

### ISSUE THREAD

**Issue by kogden** [GluuFederation/oxShibboleth#45]
So my SP post_assert block is getting this error:
```
Error: Expected 1 Assertion or 1 EncryptedAssertion; found 0
```
In my Networking tab I can see the SAMLResponse:
```
SAMLResponse=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHNhbWwycDpSZXNwb25zZSBEZXN0aW5hdGlvbj......
```

Why is my SP getting this error? I am able to login and be authenticated, this error is only thrown during the post_assert block.

```
app.post("/dashboard", function (req, res) {
  console.log("sp: Asserting login");
  var options = { request_body: req.body };
  sp.post_assert(idp, options, function (err, saml_response) {
    if (err != null){
      console.log("error in post assert \nsaml_response: " + saml_response);     // saml_response return undefined
      console.log(err);
      return res.send(500);   // currently throwing this error
    }
    console.log('running post_assert func');
    // Save name_id and session_index for logout
    last_response = saml_response.user.attributes['urn:oid:URN_ID];        // store username in variable
    name_id = saml_response.user.name_id;
    session_index = saml_response.user.session_index;

    console.log('running res.sendfile');
    res.sendfile("./dist/PAGE_FILES/index.html");
    console.log('/dashboard post complete');
  });
});
```

Here is my idp process log error. Now, my attribute-filter.xml file is actually completely empty. We've identified this as a problem already but the SP was actually working a couple days ago even with the empty file.

```
2018-09-17 14:09:47,387 - ERROR [net.shibboleth.utilities.java.support.service.AbstractReloadableService:231] - Service 'shibboleth.AttributeFilterService': Reload for shibboleth.AttributeFilterService failed
net.shibboleth.utilities.java.support.service.ServiceException: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 1 in XML document from file [/opt/shibboleth-idp/conf/attribute-filter.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at net.shibboleth.ext.spring.service.ReloadableSpringService.doReload(ReloadableSpringService.java:336)
Caused by: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 1 in XML document from file [/opt/shibboleth-idp/conf/attribute-filter.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:399)
Caused by: org.xml.sax.SAXParseException: Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
2018-09-17 14:09:49,416 - WARN [org.opensaml.saml.metadata.resolver.impl.AbstractReloadingMetadataResolver:402] - Metadata Resolver FilesystemMetadataResolver SiteSP1: Entire metadata document from '/opt/shibboleth-idp/metadata/F951A1BEAF1B974D000260183AE800067189DB97-sp-metadata.xml' was expired at time of loading, existing metadata retained
2018-09-17 14:09:49,417 - INFO [org.opensaml.saml.metadata.resolver.impl.AbstractReloadingMetadataResolver:306] - Metadata Resolver FilesystemMetadataResolver SiteSP1: Next refresh cycle for metadata provider '/opt/shibboleth-idp/metadata/F951A1BEAF1B974D000260183AE800067189DB97-sp-metadata.xml' will occur on '2018-09-17T14:14:49.417Z' ('2018-09-17T14:14:49.417Z' local time)
```

**Comment by nynymike** [comment]
This has nothing to do with the shibboleth plugin. Not even sure if it's a Gluu question, or a shibboleth question. Open on https://support.gluu.org if you think it's a Gluu issue. This github repo is only for work on the Shibboleth login handler.
