### ISSUE TITLE
oxAuth SAML plugin should support reading configuration from Couchbase

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxShibboleth#56]
Stack trace:
```
org.gluu.persist.exception.operation.ConfigurationException: Failed to create LDAP connection pool! Result code: '91'
	at org.gluu.persist.ldap.impl.LdapEntryManagerFactory.createEntryManager(LdapEntryManagerFactory.java:50)
	at org.gluu.oxauth.client.conf.Configuration.createLdapEntryManager(Configuration.java:235)
	at org.gluu.oxauth.client.conf.Configuration.create(Configuration.java:94)
	at org.gluu.oxauth.client.conf.Configuration.<init>(Configuration.java:79)
	at org.gluu.idp.externalauth.openid.conf.IdpConfiguration.<init>(IdpConfiguration.java:13)
	at org.gluu.idp.externalauth.openid.conf.IdpConfiguration$ConfigurationSingleton.<clinit>(IdpConfiguration.java:18)
```

**Comment by yurem** [comment]
Implemented
